### ISSUE TITLE
JWT validation failed: Unable to fetch verification key

### ISSUE THREAD

**Issue by Jonathan34** [cloudendpoints/esp#303]
Hi,
I have an ESP on top of both an appengine service and a k8s cluster (elastic search)

I have upgraded the esp config to talk to our prod `x-google-jwks_uri` but the esp cannot reach the url (which can be browsed.

```
{
    "code": 16,
    "message": "JWT validation failed: Unable to fetch verification key",
    "details": [
        {
            "@type": "type.googleapis.com/google.rpc.DebugInfo",
            "stackEntries": [],
            "detail": "auth"
        }
    ]
}
```

i can send the `x-google-jwks_uri` to whoever needs it. This url uses a certificate signed `Issued by: Entrust Certification Authority - L1M`.

From the appengine and k8s nginx log i can see:

`"[error] 43#43: peer closed connection in SSL handshake" `

which makes me think something is missing in the configuration for both to properly either resolve the dns or validate the certificate (which again is supposed to be public).

any thought?

**Comment by qiwzhang** [comment]
It could be https://github.com/cloudendpoints/esp/issues/271.

**Comment by Jonathan34** [comment]
this jwks-uri is actually deployed in appengine; using the appspot url instead solves the issue. it just wont allow to use the fqdn i need with the entrust cert

**Comment by lei-tang** [comment]
The error message ("JWT validation failed: Unable to fetch verification key") in this issue is the same as that of the issues https://github.com/cloudendpoints/esp/issues/262 and https://github.com/cloudendpoints/esp/issues/271, which are caused by ESP's lack of SNI (Server Name Indication) support for https clients. The support of SNI for https clients has been added to ESP by the commit 
https://github.com/cloudendpoints/esp/commit/3fe87fd99029c30ed1c919d9114675e127ffb152, which has been tested based on the instructions in https://github.com/cloudendpoints/esp/issues/271.

**Comment by lizan** [comment]
ESP [1.20.0](https://github.com/cloudendpoints/esp/releases/tag/v1.20.0) was released and contains the fix. Let me know if this solves your issue.

**Comment by eshwarprasadhu** [comment]
Hi, I have an ESP on Compute Engine and it's giving the same error message ("JWT validation failed: Unable to fetch verification key"). 
It does work when I allow all egress traffic. The expectation is the api should work with default deny egress firewall in-place. The esp container log is giving this connection timed out error.
```
2020/09/23 12:05:54 [error] 9#9: upstream timed out (110: Connection timed out)
2020/09/23 12:05:54[error]9#9: Failed to call https://servicecontrol.googleapis.com/v1/services/<myservice>:report
```

**Comment by nareddyt** [comment]
I see you filed #817 for this, let's continue discussion there.
