### ISSUE TITLE
Log JWT payload claim to endpoint logs

### ISSUE THREAD

**Issue by qiwzhang** [cloudendpoints/esp#490]
There are some requests to log JWT payload claim  to endpoint log so they can be queried in Google console.

start_esp can add a flag as

--log_jwt_payload=foo,bar

foo and bar are the names in the JWT payload claim

For example, for such payload:

{
   "iss": "[TOKEN_ISSUER]",
   "iat": [ISSUED_TIME],
   "exp": [EXPIRED_TIME],
   "aud": "[AUDIENCE]",
   "sub": "[SUBJECT]",
   "azp": "[AUTHORIZED_PARTY]",
   "google": {
    "compute_engine": {
      "project_id": "[PROJECT_ID]",
      "project_number": [PROJECT_NUMBER],
      "zone": "[ZONE]",
      "instance_id": [INSTANCE_ID],
      "instance_name": "[INSTANCE_NAME]"
      "instance_creation_timestamp": [CREATION_TIMESTAMP]
    }
  }
}

if --log_jwt_payload=sub,google.compute_engine.project_id.

endpoint log will have following fields

jwt_payload.sub = [SUBJECT]
jwt_payload.google.compute_engine.project_id = [PROJECT_ID]

**Comment by arturgspb** [comment]
I also need a definition of customer api!
I use esp locally and I have one project_id.
Well, if UserAgent logs and customized part of JWT payload.

**Comment by qiwzhang** [comment]
@arturgspb did not quite understand your request.  Which field if JWT payload do you want to log to Endpoint log?

**Comment by arturgspb** [comment]
Hi, @qiwzhang ! Thank you for your quick response. 

I need any opportunity to identify an application that works with my API. 

Problem 1. I thought it would be a good option to keep the User-Agent in the logs. It often happens that actually different scripts use the same token, and only UserAgent or something similar allows you to collect more understandable logs.

Problem 2. I myself release tokens not through Google and it turns out that I have only one Google Cloud Project id. Therefore, now the limits and quotas for the number of requests in the API do not work, and also I cannot understand which of client applications really causes API.

Today I thought that maybe there is some option in which I will issue tokens myself, but based on the google project Id for different each api client. I do not know if there is such an option. I will try to think it over better, maybe it will eliminate my problem 2, but for now I don’t know how to do it.

**Comment by qiwzhang** [comment]
@arturgspb  for your 2), you may want to take a look this [doc](https://cloud.google.com/endpoints/docs/openapi/service-account-authentication)

**Comment by arturgspb** [comment]
@qiwzhang 

Thank you, I will learn this once again better. Last time I did not find there a way to specify specific for my api scopes like. Maybe you know how to register them in a google if google will be token issuer? The fact is that only my application knows which user can get specific scopes via oauth and I have not yet understood how to make Google release tokens, but include and checked and there are my api scopes.

I really like the design of google api and I try to repeat it in my company. Here is the skeleton of the project with proto files and YAML configuration of API, where you can see how tokens are checked. Since you have more expertise in this issue, maybe you will see my mistakes and tell me how to do better.

https://github.com/devision-io/devision-apis-skeleton/blob/master/%7B%7Bcookiecutter.project_name.lower()%7D%7D/api/%7B%7Bcookiecutter.project_name.lower()%7D%7D.yaml#L21

Thanks in advance for the answer, you are very helpful!

**Comment by qiwzhang** [comment]
Are you trying to white list clients that can use your service?   You want ESP to block the services not white-listed?  is that right?

you can use a hack in JWT "aud" field.   Each client will generate JWT with its own "aud".  You can do that by following this [doc](https://cloud.google.com/endpoints/docs/openapi/service-account-authentication).  Then your service config list all "aud" are allowed in the "audience" fields in your config file line 23

**Comment by arturgspb** [comment]
No, I all clients may use my api. It's not different with google apis. But my apps use internal scopes (not google scopes from https://developers.google.com/identity/protocols/googlescopes) and my app must release tokens and check they.

**Comment by arturgspb** [comment]
@qiwzhang , what about "User Agent" header logging?
