### ISSUE TITLE
Upgrading to v1.29.0 appears to break ESP for URL's with query parameters

### ISSUE THREAD

**Issue by andrew-canaday** [cloudendpoints/esp#535]
We ran into an issue today while deploying a handful of services using ESP with the `:1` tag. It appears that as of the `v1.29.0` release, query strings which contain parameters in the format `name=val` result in HTTP `400` errors, 100% of the time.

We have mitigated by rolling back to `1.28.0` tag, but wanted to surface for anyone else using `:1` and "always pull" policy on their respective platform.

**Comment by andrew-canaday** [comment]
Some evidence this may not be the case. Closing and will re-open after further investigation. _Sorry for the noise_.

**Comment by andrew-canaday** [comment]
This has been reproducible on all of our Java/Jetty-based services.
It is unconfirmed on our node.js services, but figured I'd re-open as others running at latest may want to verify.

Thanks much!

**Comment by qiwzhang** [comment]
is HTTP 400 responded by ESP?  

I don't remember ESP ever replied 400.  If a path is not configured,  it will replied 404.

If using container to deploy ESP,  could you turn on debug by add start_esp flag --enable_debug

and get the ESP log from inside the container  /var/log/nginx/error.log

Thanks

**Comment by andrew-canaday** [comment]
_Thank you_ for responding so quickly.
I'll get the details tomorrow and update the issue.
My apologies if this turns out to be a quirk in jetty/whatever, but figured better safe than sorry due to the ubiquity of this thing.

Thanks much! Will reach out tomorrow. 👍

**Comment by andrew-canaday** [comment]
Sorry for the lag @qiwzhang. On this shortly

**Comment by andrew-canaday** [comment]
Still behind. Will gather data from our systems. We did have another event in the company today (another java-based team) where upgrading to `1.29.0` resulted in service outage for them.

**Comment by qiwzhang** [comment]
@andrew-canaday we found the issue.  We are rolling back ESP 1.29.0

**Comment by qiwzhang** [comment]
ESP release 1.29.0 is rolled back.

https://b.corp.google.com/issues/124016577#comment24

**Comment by andrew-canaday** [comment]
@qiwzhang Thank you for the progress/updates (despite the lack of input on my end!). I'm content for this issue to be closed out however best fits your usual work-flow:
 * that the issue was recognized, and the major version rolled-back is _sufficient on my end_
 * if you'd like to close after you are satisfied that the root cause has been fixed: _great_
 * if you'd like independent verification after patching: it'll be a simple matter for me to bump one of our services up to the next release and check it again

Thanks!

**Comment by qiwzhang** [comment]
I like to add some more details in case some users run into the same issue

1) the bug is introduced by this PR: https://github.com/cloudendpoints/esp/pull/514.  It has an un-initialized variable that is checked to manipulate the url path send to the backend.  

2) If your request has query parameters, such as /path?key1=val1,  and backend is http, randomly at each ESP starts, (since it is an initialized variable at config loading time), the path send to the backend because ?key1=val1  which causes the backend server to reject the request.  This problem will not happen if the backend is gRPC since the modified path is not used.

3) The PR to fix this is:  https://github.com/cloudendpoints/esp/pull/542

4) Next ESP release 1.30.0, will have the fix.
