### ISSUE TITLE
Replace oauth2client with google-auth and oauthlib

### ISSUE THREAD

**Issue by farmdawgnation** [cloudendpoints/esp#704]
oauth2client is deprecated and doesn't behave well when credentials are presented of the `authorized_user` type or provide built-in support for application default credentials. Updating the new libraries such that we could use the `authorized_user` credentials would avoid us having to populate a secret to our local dev environments.

**Comment by qiwzhang** [comment]
https://github.com/cloudendpoints/esp/pull/706

**Comment by qiwzhang** [comment]
#706 is causing some problems.   Hence this issue is revisited to see if the changes actually address your problems.  

oauth2client is used to generate access_token from a service account json file to access Google services.   There are two parts of code generating access token:
1) python code in start_esp.py.  It is using oauth2client.  This is for ESP to talk to Google service management service to fetch service config before Nginx starts.
2) c++ code inside Nginx.  This is for actual requests to call Google service control service.

Even we change python code to replace oauth2client,  but we could not change c++ code for that.  Not sure if it will address your local dev issues by replacing oauth2client.

**Comment by farmdawgnation** [comment]
Last I checked, the python code was explicitly checking the type of the credentials presented were `service_account` so my `authorized_user` credentials didn't cut it.

Let me see if I can find time to test this out in the next few days and get back to you. (I was in a training class all of last week)

**Comment by qiwzhang** [comment]
Well,  we fixed the problem of using google-auth.  It is a forward moving step to replace deprecated oauthlib.
