### ISSUE TITLE
Forward Authorization

### ISSUE THREAD

**Issue by legithubdeaymeric** [cloudendpoints/esp#771]
From https://cloud.google.com/endpoints/docs/openapi/authenticating-users-custom

> "ESP usually forwards all headers it receives. However, it overrides the original Authorization header when the backend address is specified by x-google-backend in OpenAPI specification or BackendRule in gRPC service configuration."

Hello,

But is there a way to forward the original authorization?
We had API legacy which uses a basic authorization... 

Thanks !

**Comment by TAOXUY** [comment]
Hello, 

Actually we have a new feature in [ESPv2](https://github.com/GoogleCloudPlatform/esp-v2) just coming out for the location of jwtToken, allowing users to preserve their token instead of overwriting by proxy. We will update the [doc](https://cloud.google.com/endpoints/docs/openapi/restricting-api-access-with-api-keys) soon to explain more.

Unfortunately, we haven't implemented it yet on ESP side.

**Comment by nareddyt** [comment]
@legithubdeaymeric, are you deploying on serverless (cloud run, cloud functions) or normal compute (GCE, GKE)? 
- If you are deploying on serverless, we recommend you use ESPv2. Then you can use the feature @TAOXUY mentioned.
- If you are deploying as a sidecar on regular compute, then you don't need to worry about it. It only overwrites the header when connecting to remote backends via the `BackendRule`. For local backends, it will not change the `Authorization` header.

**Comment by TAOXUY** [comment]
Hello @legithubdeaymeric ,

The comments of @nareddyt  is quite complete. 

Forget to mention if you don't need IAP/IAM for the authn of your remote backend, you can use [`disable_auth`](https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#jwt_audience_disable_auth)field. Remember you may need your own authn logic to protect your backend.

If you still need the remote backend auth from IAP/IAM, currently no solution on ESPv1 and you may choose to migrate to ESPv2 if possible(we have officially doc ESPv2 for [Serverless](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-run)). If not, what is the concern?

**Comment by jprotin** [comment]
Hello @TAOXUY  & @nareddyt ,

Thank you very much, it's very clear.

Is it possible to override the ESPv1 Docker to duplicate a new header (ex: X-Auhtorization) and add an algorithm to copy the original Authorization value  to the new header ?
Thus with continous with IAP/IAM and the new header with our authentification ?
If it's possible, do you know how ?
If not, I think we listen your precious advizes.
The objective, it's to keep the Service account authentification between Endpoint API + ESPv1 and our backend with App-Engine. 

@legithubdeaymeric 

Best.

**Comment by qiwzhang** [comment]
We could move the original Authorization header to X-Forwarded-Authorization header.  Will that help?

If you want to do it on your own, you can place another proxy, such as Nginx, in front of ESP to duplicate this header.  But it is overkill.

**Comment by jprotin** [comment]
Hi @qiwzhang 

> We could move the original Authorization header to X-Forwarded-Authorization header. Will that help?

Yeah, it's the idea. We redesign an existing api on-premise, and our customers already use Authorization in the headers for the connection. We must keep a backwards compatibility.
Moving the original Authorization header to another X-Forwarded-Authorization header is a good idea, so we could use this header on our backend for the client connection and keep IAP/IAM between endpoint+ESP and our backend with app-engine.

> If you want to do it on your own, you can place another proxy, such as Nginx, in front of ESP to duplicate this header. But it is overkill.
 It's overkill yeah :) but is it possible to do this between Endpoint and ESP proxy?

Many thanks.

**Comment by qiwzhang** [comment]
You mean in the same docker image, in the same container with ESP, you want to duplicate a http header.   It is possible,  but you need to write a lot of code, you need to understand how our container entry script works in order to hook up your code.  I would not recommend it.

I feel adding x-forwarded-authorization header is a good idea.  Other users may need it too.  We will add it in both ESPv1 and ESPv2 release.  You can wait for it,  it should be available in 2, 3 weeks.

**Comment by jprotin** [comment]
Hi @qiwzhang 

Quick question to understand, if the Authorization header is sent by our customers, the value sent will be automatically transmitted into the X-Forwarded-Authorization via the ESP proxy? Or X-Forwarded-Authorization will have to be sent by our customers?

If we can wait 2, 3 weeks, it's ok because we will disable IAP/IAM between endpoint api + ESP prox and App-engine until we have a reliable solution.

**Comment by qiwzhang** [comment]
You customers will still set "Authorization" header as before.  ESP will move it to X-Forwarded-Authorization header.

**Comment by jprotin** [comment]
Perfect ! It's exactly we want :)

**Comment by qiwzhang** [comment]
https://github.com/cloudendpoints/esp/pull/772
